# tabuada
n1 = int(input('digite um numero inteiro: '))
print('-------------')
print(n1,'x 0 = {}'.format(n1*0))
print(n1,'x 1 = {}'.format(n1*1))
print(n1,'x 2 = {}'.format(n1*2))
print(n1,'x 3 = {}'.format(n1*3))
print(n1,'x 4 = {}'.format(n1*4))
print(n1,'x 5 = {}'.format(n1*5))
print(n1,'x 6 = {}'.format(n1*6))
print(n1,'x 7 = {}'.format(n1*7))
print(n1,'x 8 = {}'.format(n1*8))
print(n1,'x 9 = {}'.format(n1*9))
print(n1,'x 10 = {}'.format(n1*10))
print('-------------')